[default]
output = "./storage/model/"
connect = "dt/config/dbconnect"

[[db]]
# 目标数据库
target_url = "root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local"
# 源数据库
origin_url = "root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local"
# 源数据库
connect = "dt/config/dbconnect"
output = "./storage/model/"

# 可以配置多个
#[[db]]
## 目标数据库
#target_url = "root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local"
## 源数据库
#origin_url = "root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local"
## 源数据库
#connect = "dt/config/dbconnect"
#output = "./storage/model/"
#[[db]]
## 目标数据库
#target_url = "root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local"
## 源数据库
#origin_url = "root:root_password@tcp(127.0.0.1:3306)/thh_database?charset=utf8mb4&parseTime=True&loc=Local"
## 源数据库
#connect = "dt/config/dbconnect"
#output = "./storage/model/"